version: "3"

volumes:
  esdata01:
    driver: local

networks:
  backend:
  frontend:
    driver: bridge # use the bridge driver
    ipam:
      driver: default


services:
  bootstrap:
    hostname: bootstrap
    container_name: bootstrap01
    image: enigmampc/worker_hw:latest
    depends_on:
      - contract
      - km
    environment:
      ENIGMA_ENV: COMPOSE
      SGX_MODE: HW
      BOOTSTRAP: "TRUE"
    expose:
      - "10300" # libp2p port
      - "8080"  # what is this?
      - "3346"
    devices:
      - "/dev/isgx:/dev/isgx"
      - "/dev/mei0:/dev/mei0"
  worker:
    hostname: worker
    image: enigmampc/worker_hw:latest
    depends_on:
      - contract
      - km
    environment:
      ENIGMA_ENV: COMPOSE
      SGX_MODE: HW
    devices:
      - "/dev/isgx:/dev/isgx"
      - "/dev/mei0:/dev/mei0"
    expose:
      - "8080" # what is this?
      - "9229"
      - "3346"

  contract:
    hostname: contract
    container_name: contract
    image: enigmampc/contract_hw:latest
    devices:
      - "/dev/isgx:/dev/isgx"
      - "/dev/mei0:/dev/mei0"
    environment:
      SGX_MODE: HW
      ENIGMA_ENV: COMPOSE
    ports:
      - "8081:8081" # contract discovery service
      - "9545:9545" # ethereum node port
      - "8001:8001" # faucet port

  km:
    hostname: km
    container_name: km
    image: enigmampc/key_management_hw:latest
    devices:
      - "/dev/isgx:/dev/isgx"
      - "/dev/mei0:/dev/mei0"
    environment:
      ENIGMA_ENV: COMPOSE
      SGX_MODE: HW
    expose:
      - "3040" # JSON RPC port

  client:
    hostname: client
    image: enigmampc/client:latest
    stdin_open: true
    tty: true
    depends_on:
      - contract
    environment:
      ENIGMA_ENV: COMPOSE
