name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker images
      run: |
        make clone-all
        echo make build SGX_MODE=SW
    - name: Run the tests
      run: |
        cp .env.template .env
        echo docker-compose up --exit-code-from client & sleep 240 && docker-compose exec -T client make test

on:
  push:
    branches:
      - test

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy images
        run: echo "Building and deploying"